"""empty message

Revision ID: fc7461a0bc42
Revises: 76d840af60c3
Create Date: 2020-05-09 15:51:00.831089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7461a0bc42'
down_revision = '76d840af60c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE todos SET list_id = 1 WHERE list_id is null;')

    op.alter_column('todos', 'list_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
